---
kind: pipeline
type: docker
name: verify
steps:
- name: install
  image: danlynn/ember-cli:5.3.0-node_18.18
  commands:
  - npm install
- name: lint
  image: danlynn/ember-cli:5.3.0-node_18.18
  commands:
  - npm run lint
- name: test
  image: danlynn/ember-cli:5.3.0-node_18.18
  failure: ignore
  commands:
  - npm run test:ember
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: npm-release
  image: plugins/npm
  settings:
    token:
      from_secret: npm_access_token
trigger:
  event:
    - tag
---
kind: secret
name: npm_access_token
data: Ja3CLl246izVXpfbwkwoRp3Oi9f/KAYzs/I4kKMKKt8VZHrfojgHzA2JTlqTwrEaFOiqxTbxA9WziTZ67Ct2z4ZoaCg=
