matrix:
  scenario:
    - ember-lts-4.8
    - ember-lts-5.12
    - embroider-optimized
    - ember-simple-auth-v6
steps:
  - name: ${scenario}
    image: danlynn/ember-cli:6.2.1-node_22.14
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
      - pnpm --filter test-app exec ember try:one ${scenario} --skip-cleanup

when:
  event:
    - pull_request
