steps:
  install:
    image: danlynn/ember-cli:6.2.1-node_22.14
    commands:
      - npm ci
  lint:
    image: danlynn/ember-cli:6.2.1-node_22.14
    commands:
      - npm run lint
  test:
    image: danlynn/ember-cli:6.2.1-node_22.14
    commands:
      - npm run test
when:
  event:
    - pull_request
