steps:
  release:
    image: node:22.14
    commands:
      - npm ci
      - npm config set //registry.npmjs.org/:_authToken $NPM_ACCESS_TOKEN
      - npm run build
      - npm publish --workspace ember-address-search
    secrets: [npm_access_token]
when:
  event: tag
  ref: refs/tags/v*
